"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApolloItem = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
/**
 * ApolloItem for apolloconfig
 */
class ApolloItem extends pulumi.CustomResource {
    /**
     * Get an existing ApolloItem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, opts) {
        return new ApolloItem(name, undefined, Object.assign(Object.assign({}, opts), { id: id }));
    }
    /**
     * Returns true if the given object is an instance of ApolloItem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApolloItem.__pulumiType;
    }
    /**
     * Create a ApolloItem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name, args, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.clusterName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterName'");
            }
            if ((!args || args.env === undefined) && !opts.urn) {
                throw new Error("Missing required property 'env'");
            }
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if ((!args || args.namespace === undefined) && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["dataChangeCreatedBy"] = args ? args.dataChangeCreatedBy : undefined;
            resourceInputs["dataChangeLastModifiedBy"] = args ? args.dataChangeLastModifiedBy : undefined;
            resourceInputs["env"] = args ? args.env : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["namespace"] = args ? args.namespace : undefined;
            resourceInputs["operator"] = args ? args.operator : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
        }
        else {
            resourceInputs["appId"] = undefined /*out*/;
            resourceInputs["clusterName"] = undefined /*out*/;
            resourceInputs["comment"] = undefined /*out*/;
            resourceInputs["dataChangeCreatedBy"] = undefined /*out*/;
            resourceInputs["dataChangeLastModifiedBy"] = undefined /*out*/;
            resourceInputs["env"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
            resourceInputs["operator"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["appId", "clusterName", "env", "key", "namespace"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ApolloItem.__pulumiType, name, resourceInputs, opts);
    }
}
exports.ApolloItem = ApolloItem;
/** @internal */
ApolloItem.__pulumiType = 'apolloconfig:index:ApolloItem';
//# sourceMappingURL=apolloItem.js.map