"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Provider = exports.ApolloItem = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
exports.ApolloItem = null;
utilities.lazyLoad(exports, ["ApolloItem"], () => require("./apolloItem"));
exports.Provider = null;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "apolloconfig:index:ApolloItem":
                return new exports.ApolloItem(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("apolloconfig", "index", _module);
pulumi.runtime.registerResourcePackage("apolloconfig", {
    version: utilities.getVersion(),
    constructProvider: (name, type, urn) => {
        if (type !== "pulumi:providers:apolloconfig") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new exports.Provider(name, undefined, { urn });
    },
});
//# sourceMappingURL=index.js.map